### ISSUE TITLE
A lot of warnings on armcc

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/uvisor-lib#18]
When compiling any example there is a long list of warnings generated, everyone the same though:

```
"./example-asynch-spi/yotta_modules/uvisor-lib/uvisor-lib/vmpu_exports.h", line 124: Warning:  #368-D: class "<unnamed>" defines no constructor to initialize the following:
            const member "<unnamed>::acl_list"
  {
```

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSFW-1069

**Comment by meriac** [comment]
@AlessandroA

**Comment by AlessandroA** [comment]
This should be fixed now. @niklas-arm could you please double check? Feel free to reopen if the issue reappears.
