### ISSUE TITLE
Run-time exception is thrown when using NULL for ACLs

### ISSUE THREAD

**Issue by mottigondabi** [ARMmbed/uvisor-lib#22]
Using "UVISOR_BOX_CONFIG(...)" to configure secure box compartment without ACL end up with run-time exception.

Example:
UVISOR_BOX_CONFIG(my_box_name, NULL, SOME_BOX_STACK_SIZE, BoxContext);

And this example fail to work as well:
static const UvisorBoxAclItem my_acl[] = { };
UVISOR_BOX_CONFIG(my_box_name, my_acl, SOME_BOX_STACK_SIZE, BoxContext);

-Motti.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1511
